### ISSUE TITLE
Error on loading a new or saved game.

### ISSUE THREAD

**Issue by Xudmud** [RitnDev/RitnLib#1]
![image](https://github.com/RitnDev/RitnLib/assets/14797807/31224fdc-b744-4ec1-b695-0d0cd52f1ca5)

It looks like the mod is trying to load `luaLib/informatron/menu` and not `lualib/informatron/menu` and thus throwing the error on any game load.

Steps of reproduction:
1. Start up Factorio
2. Start a new game or load an existing save.

Expected result:
The game loads into the map and can be played.

Actual result:
The game kicks back to the title screen with the above error message.

**Comment by transparentmask** [comment]
Same issue, play with macOS. I fix it local with using "lualib" in core/interfaces.lua. It works.

**Comment by RitnDev** [comment]
Hi, 
The latest versions released do not correct the problem ?
-> RitnLib 0.8.5

**Comment by transparentmask** [comment]
> Hi, The latest versions released do not correct the problem ?
Yes, version 0.8.5 report this.

**Comment by RitnDev** [comment]
Could you provide me with the list of your used mods along with their respective versions?

**Comment by RitnDev** [comment]
RitnLib 0.8.6 fix issues ;)
